name: Testes de API com PactumJS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2

      - name: Configuração do Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Instalação das dependências
        run: npm ci

      - name: Execução dos testes
        run: npm run test
        
